#!/bin/bash

find ../themes/neopoligen.com/ -type f -name "*.neotest" -print0 \
| xargs -0 \
sed -i "" 's|{{-|[@|g;s|{{|[@|g;s|-}}|@]|g;s|}}|@]|g;s|{%-|[!|g;s|{%|[!|g;s|-%}|!]|g;s|%}|!]|g;s|{#-|[#|g;s|{#|[#|g;s|-#}|#]|g;s|#}|#]|g'
